<?php

namespace Yuforms\Api\Config;

class Endpoint {
    const ENDPOINT = [
        'Example'=>[
            'POST'=>[
                'authorization'=>['guest', 'member', 'root'],
                    /*
                'required'=>[
                    'name'=>[
                        'type'=>'str', // str, arr, int, email, bool
                        'limits'=>[
                            'min'=>0,
                            'max'=>10
                        ]
                    ],
                    'surname'=>[
                        'type'=>'str', // str, arr, int
                        'limits'=>[
                            'min'=>0,
                            'max'=>30
                        ]
                    ],
                    'other'=>[
                        'other1'=>[
                            'type'=>'str', // str, arr, int
                            'limits'=>[
                                'min'=>0,
                                'max'=>30
                            ]
                        ],
                        'other2'=>[
                            'type'=>'str', // str, arr, int
                            'limits'=>[
                                'min'=>0,
                                'max'=>30
                            ]
                        ],
                    ]
                ]*/
            ],
            'GET'=>[
                'authorization'=>['guest', 'member', 'root'],
                'required'=>[
                    'isBoolean'=>[
                        'type'=>'bool'
                    ]
                ]
            ],
            'PUT'=>[
                'authorization'=>['guest', 'member', 'root'],
            ],
            'PATCH'=>[
                'authorization'=>['guest', 'member', 'root'],
            ],
            'DELETE'=>[
                'authorization'=>['guest', 'member', 'root'],
            ]
        ],
        'SignUp'=>[
            'POST'=>[
                'authorization'=>['guest'],
                'required'=>[
                    'email'=>[
                        'type'=>'email',
                        'limits'=>[
                            'min'=>1,
                            'max'=>255
                        ]
                    ],
                    'firstName'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>1,
                            'max'=>50
                        ]
                    ],
                    'lastName'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>1,
                            'max'=>50
                        ]
                    ],
                    'password'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>10,
                            'max'=>50
                        ]
                    ]
                ]
            ]
        ],
        'ConfirmEmail'=>[
            'POST'=>[
                'authorization'=>['guest'],
                'required'=>[
                    'email'=>[
                        'type'=>'email',
                        'limits'=>[
                            'min'=>1,
                            'max'=>255
                        ]
                    ],
                    'code'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>6,
                            'max'=>6
                        ]
                    ]
                ]
            ]
        ],
        'Login'=>[
            'POST'=>[
                'authorization'=>['guest'],
                'required'=>[
                    'email'=>[
                        'type'=>'email',
                        'limits'=>[
                            'min'=>1,
                            'max'=>255
                        ]
                    ],
                    'password'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>10,
                            'max'=>50
                        ]
                    ]
                ]
            ],
            'PATCH'=>[
                'authorization'=>['guest'],
                'required'=>[
                    'email'=>[
                        'type'=>'email',
                        'limits'=>[
                            'min'=>1,
                            'max'=>255
                        ]
                    ],
                    'authenticationCode'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>0,
                            'max'=>10
                        ]
                    ]
                ]
            ]
        ],
        'ForgotMyPassword'=>[
            'POST'=>[
                'authorization'=>['guest'],
                'required'=>[
                    'email'=>[
                        'type'=>'email',
                        'limits'=>[
                            'min'=>1,
                            'max'=>255
                        ]
                    ]
                ]
            ],
            'PATCH'=>[
                'authorization'=>['guest'],
                'required'=>[
                    'email'=>[
                        'type'=>'email',
                        'limits'=>[
                            'min'=>1,
                            'max'=>255
                        ],
                    ],
                    'code'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>10,
                            'max'=>10
                        ]
                    ],
                    'newPassword'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>10,
                            'max'=>50
                        ]
                    ]
                ]
            ]
        ],
        'ChangeMyPassword'=>[
            'PATCH'=>[
                'authorization'=>['member'],
                'required'=>[
                    'password'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>10,
                            'max'=>50
                        ]
                    ],
                    'newPassword'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>10,
                            'max'=>50
                        ]
                    ]
                ]
            ]
        ],
        'ChangeMyEmail'=>[
            'PATCH'=>[
                'authorization'=>['member'],
                'required'=>[
                    'password'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>10,
                            'max'=>50
                        ]
                    ],
                    'newEmail'=>[
                        'type'=>'email',
                        'limits'=>[
                            'min'=>1,
                            'max'=>255
                        ]
                    ]
                ]
            ]
        ],
        'LogOut'=>[
            'POST'=>[
                'authorization'=>['member']
            ]
        ],
        'Form'=>[
            'POST'=>[
                'authorization'=>['member'],
            ],
            'GET'=>[
                'authorization'=>['member'],
                'required'=>[
                    'slug'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>1,
                            'max'=>100
                        ]
                    ]
                ]
            ],
            'PUT'=>[
                'authorization'=>['member'],
                'required'=>[
                    'id'=>[
                        'type'=>'int',
                        'limits'=>[
                            'min'=>1,
                            'max'=>11
                        ]
                    ],
                    'formTitle'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>1,
                            'max'=>256
                        ]
                    ],
                    'questions'=>[
                        'type'=>'arr',
                        'limits'=>[
                            'min'=>1,
                            'max'=>50  // actually there isn't top limit, I can change it
                        ]
                    ]
                ]
            ],
            'DELETE'=>[
                'authorization'=>['member'],
                'required'=>[
                    'id'=>[
                        'type'=>'int',
                        'limits'=>[
                            'min'=>1,
                            'max'=>11
                        ]
                    ]
                ]
            ]
        ],
        'Share'=>[
            'POST'=>[
                'authorization'=>['member'],
                'required'=>[
                    'formId'=>[
                        'type'=>'int',
                        'limits'=>[
                            'min'=>1,
                            'max'=>11
                        ]
                    ],
                    'onlyMember'=>[
                        'type'=>'bool',
                    ]
                ]
            ],
            'DELETE'=>[
                'authorization'=>['member'],
                'required'=>[
                    'formId'=>[
                        'type'=>'int',
                        'limits'=>[
                            'min'=>1,
                            'max'=>11
                        ]
                    ]
                ]
            ],
            'PUT'=>[
                'authorization'=>['member'],
                'required'=>[
                    'formId'=>[
                        'type'=>'int',
                        'limits'=>[
                            'min'=>1,
                            'max'=>11
                        ]
                    ],
                    'onlyMember'=>[
                        'type'=>'bool',
                    ]
                ]
            ]
        ],
        'Submit'=>[
            'GET'=>[
                'authorization'=>['guest', 'member'],
                'required'=>[
                    'formSlug'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>1,
                            'max'=>100
                        ]
                    ]
                ]
            ],
            'POST'=>[
                'authorization'=>['guest', 'member'],
                'required'=>[
                    'formSlug'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>1,
                            'max'=>100
                        ]
                    ],
                    'answers'=>[
                        'type'=>'arr',
                        'limits'=>[
                            'min'=>1,
                            'max'=>100
                        ]
                    ]
                ]
            ],
            'PUT'=>[
                'authorization'=>['guest', 'member'],
                'required'=>[
                    'formSlug'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>1,
                            'max'=>100
                        ]
                    ],
                    'answers'=>[
                        'type'=>'arr',
                        'limits'=>[
                            'min'=>1,
                            'max'=>100
                        ]
                    ]
                ]
            ]
        ],
        'ListMyForms'=>[
            'GET'=>[
                'authorization'=>['member']
            ],
        ],
        'Template'=>[
            'POST'=>[
                'authorization'=>['member'],
                'required'=>[
                    'formId'=>[
                        'type'=>'int',
                        'limits'=>[
                            'min'=>1,
                            'max'=>11
                        ]
                    ],
                    'name'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>1,
                            'max'=>256
                        ]
                    ],
                ]
            ],
            'DELETE'=>[
                'authorization'=>['member'],
                'required'=>[
                    'formId'=>[
                        'type'=>'int',
                        'limits'=>[
                            'min'=>1,
                            'max'=>11
                        ]
                    ],
                ]
            ],
            'PUT'=>[
                'authorization'=>['member'],
                'required'=>[
                    'formId'=>[
                        'type'=>'int',
                        'limits'=>[
                            'min'=>1,
                            'max'=>11
                        ]
                    ],
                    'formTitle'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>1,
                            'max'=>256
                        ]
                    ],
                    'questions'=>[
                        'type'=>'arr',
                        'limits'=>[
                            'min'=>0,
                            'max'=>50  // actually there isn't top limit, I can change it
                        ]
                    ]
                ]
            ],
            'PATCH'=>[
                'authorization'=>['member'],
                'required'=>[
                    'formId'=>[
                        'type'=>'int',
                        'limits'=>[
                            'min'=>1,
                            'max'=>11
                        ]
                    ],
                    'public'=>[
                        'type'=>'bool',
                    ]
                ]
            ],
            'GET'=>[
                'authorization'=>['member'],
                'required'=>[
                    'formId'=>[
                        'type'=>'int',
                        'limits'=>[
                            'min'=>1,
                            'max'=>11
                        ]
                    ]
                ]
            ]
        ],
        'Manage2FA'=>[
            'PATCH'=>[
                'authorization'=>['member'],
                'required'=>[
                    'password'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>10,
                            'max'=>50
                        ]
                    ]
                ],
            ],
            'POST'=>[
                'authorization'=>['member'],
                'required'=>[
                    'open'=>[
                        'type'=>'bool',
                    ],
                    'authenticationCode'=>[
                        'type'=>'str',
                        'limits'=>[
                            'min'=>0,
                            'max'=>10
                        ]
                    ]
                ]
            ],
        ],
    ];
}
